[package]
name = "hello-hot"
version = "0.1.0"
authors = ["Xiangmin Liu <635750556@qq.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
listenfd = "0.3"
serde = "1.0.89"
serde_json = "1.0.39"
serde_derive = "1.0.89"
futures = "0.1.23"
bytes = "0.4.12"
failure = "0.1.5"
