[package]
name = "b35"
version = "0.1.0"
authors = ["XiangMin Liu <635750556@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure="0.1.2"
failure_derive="0.1.2"
