[package]
name = "serde-basic"
version = "0.1.0"
authors = ["Xiangmin Liu <635750556@qq.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7.1"
